version: '3.8'

services:
  solr-admin-x-staging:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Mount external config directory with staging config
      - ./config:/app/config:ro
    environment:
      - NODE_ENV=staging
      # Use external config file for staging
      - DC_CONFIG_PATH=/app/config/dc-data.staging.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - solr-admin-network

networks:
  solr-admin-network:
    driver: bridge
