name: 💬 Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 💬 We're here to help.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Setup/Installation
        - Configuration
        - Usage/How-to
        - Development
        - Docker/Deployment
        - API/Integration
        - Performance
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your setup or what you're trying to achieve
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - Any relevant configuration details?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Please provide your environment details if relevant to your question
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node.js: [e.g., v22.14.0]
        - Docker: [e.g., v24.0.0]
        - Browser: [e.g., Chrome 119, Firefox 118]

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true
